version: '3.8'
 
services:
  app:
    image: ${DOCKER_USERNAME}/docker-cicd-app:${IMAGE_TAG:-latest}
    ports:
      - "3001:3000"
    env_file:
      - config/environments/staging.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
